name: 'lab_2'
version: '1.0.0'
config-version: 2

# Must match the profile name in profiles.yml
profile: 'lab_2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lab_2:
    +materialized: view       # default materialization

    output:
      +materialized: table    # final models in models/output/* will be TABLES

    input:
      +materialized: ephemeral  # models in models/input/* will be EPHEMERAL
